[NEW]: Exemplos de biblioteca de icones
BiancaPereira/ninja-em-css pull request #22
Opened 2022-10-08 16:20 UTC by Amad3eu

2022-10-20 12:03 UTC, BiancaPereira requested changes
Revisar comentários

2022-10-20 22:45 UTC, Amad3eu reviewed
como assim bandeirinhas de linguagem?

2022-10-20 22:53 UTC, Amad3eu commented on README.md
> +- [FontAwesome](https://fontawesome.com/)
Corrigido😁😁😁

2022-10-24 12:48 UTC, BiancaPereira approved these changes

2022-10-24 12:48 UTC, merged

2022-10-24 12:49 UTC, BiancaPereira commented
Obrigada!! Aprovado ❤️